### ISSUE TITLE
$ npm start command Fails on Windows and Mac Environments

### ISSUE THREAD

**Issue by TonyVT** [planetoftheweb/expressjs#5]
Hello Ray,

I going through your lynda.com ,**Building a Website with Node.js and Express.js** course on the Windows and Mac environments. In both cases, I'm encountering a problem with the **npm start** command. As a result of this, I am at a standstill to complete your course. 
[npm-debug.pdf](https://github.com/planetoftheweb/expressjs/files/737481/npm-debug.pdf)
[npm-debug.pdf](https://github.com/planetoftheweb/expressjs/files/737482/npm-debug.pdf)
[npm-debug.pdf](https://github.com/planetoftheweb/expressjs/files/737483/npm-debug.pdf)
[npm-debug.pdf](https://github.com/planetoftheweb/expressjs/files/737485/npm-debug.pdf)

I'm encountering the problem while viewing "Using the exercises for this course", in the Introduction section.

Here is the message as displayed in the Git Bash terminal window:

npm ERR! Failed at the expressjs@1.0.0 start script 'nodemon -e css,ejs,js,json --watch app --ignore feedback.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the expressjs package,
npm ERR! not with npm itself.
npm ERR! **Tell the author that this fails on your system:**
npm ERR!     nodemon -e css,ejs,js,json --watch app --ignore feedback.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs expressjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls expressjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\QService.WIN-S25S85JNN0I\Desktop\expressjs\npm-debug.log

Unfortunately, I attached the log file several times.
Can you please help so that I can continue with the very important course.

Kind regards,
Tony Ventura
www.tonyventura.com

**Comment by planetoftheweb** [comment]
Please make sure you install nodemon. There is an overlay that mentions this and if you take the class in order, you also get some instructions on how to install it, but when you first clone the repo, it's not installed.

**Comment by TonyVT** [comment]
Excellent, thank you so much for responding to my request for help. I'll check overlay instructions.

Best regards,
Tony Ventura
