### ISSUE TITLE
This fails on my system

### ISSUE THREAD

**Issue by meansean13** [planetoftheweb/expressjs#8]
Hello,
I think my system is set up properly, however I am unable to start the server with the npm start command. Please find attached the the npm-debug log for reference.

Thank you for your assistance. I'm really looking forward to taking this course.

[npm-debug.txt](https://github.com/planetoftheweb/expressjs/files/982109/npm-debug.txt)

**Comment by planetoftheweb** [comment]
Looks like this may be a node incompatibility and not something related to the course. Try upgrading your node version with NVM. https://github.com/creationix/nvm
